filter:
    paths: [src/*]
    excluded_paths: [tests/*]

checks:
    php:
        code_rating: true

tools:
    external_code_coverage:
        timeout: 600
        runs: 3
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']

